module.exports = [
// ─── Indian ────────────────────────────────────────────────
  {
    name: 'Butter Chicken',
    description: 'Tender chicken pieces simmered in a rich, creamy tomato-based sauce with aromatic spices and butter.',
    price: 14.99,
    category: 'Indian',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    veg: false,
    tags: ['spicy', 'classic', 'creamy'],
    bestSeller: true,
  },
  {
    name: 'Paneer Butter Masala',
    description: 'Soft cottage cheese cubes in a velvety, rich and creamy buttery tomato gravy.',
    price: 12.50,
    category: 'Indian',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    veg: true,
    tags: ['vegetarian', 'creamy'],
    bestSeller: false,
  },
  {
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils and kidney beans in a creamy, buttery gravy. A North Indian classic.',
    price: 11.99,
    category: 'Indian',
    imageUrl: '/uploads/dal-makhani.jpg',
    rating: 4.7,
    veg: true,
    tags: ['vegetarian', 'comfort food'],
    bestSeller: true,
  },
  {
    name: 'Tandoori Chicken',
    description: 'Marinated chicken roasted in a traditional clay oven with yogurt and aromatic spices.',
    price: 15.99,
    category: 'Indian',
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    veg: false,
    tags: ['grilled', 'signature', 'smoky'],
    bestSeller: true,
  },
  // ─── South Indian ─────────────────────────────────────────
  {
    name: 'Masala Dosa',
    description: 'Crispy golden rice and lentil crepe filled with spiced potato filling, served with chutneys and sambar.',
    price: 10.99,
    category: 'South Indian',
    imageUrl: '/uploads/masala-dosa.jpg',
    rating: 4.7,
    veg: true,
    tags: ['crispy', 'breakfast'],
    bestSeller: true,
  },
  {
    name: 'Hyderabadi Biryani',
    description: 'Aromatic basmati rice layered with tender meat, saffron, and whole spices, slow-cooked to perfection.',
    price: 16.99,
    category: 'South Indian',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    veg: false,
    tags: ['spicy', 'signature', 'aromatic'],
    bestSeller: true,
  },
  {
    name: 'Idli Sambar',
    description: 'Fluffy steamed rice cakes served with piping hot lentil sambar and fresh coconut chutney.',
    price: 8.99,
    category: 'South Indian',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    veg: true,
    tags: ['healthy', 'breakfast'],
    bestSeller: false,
  },
  {
    name: 'Chettinad Chicken',
    description: 'Fiery and aromatic chicken curry from Tamil Nadu, made with freshly ground spices.',
    price: 15.50,
    category: 'South Indian',
    imageUrl: '/uploads/chettinad-chicken.jpg',
    rating: 4.6,
    veg: false,
    tags: ['spicy', 'bold'],
    bestSeller: false,
  },
  // ─── Chinese ──────────────────────────────────────────────
  {
    name: 'Hakka Noodles',
    description: 'Wok-tossed noodles with crisp vegetables, soy sauce, and a hint of chili. Indo-Chinese favorite.',
    price: 11.99,
    category: 'Chinese',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    veg: true,
    tags: ['wok', 'noodles'],
    bestSeller: false,
  },
  {
    name: 'Chilli Chicken',
    description: 'Crispy deep-fried chicken bites tossed with peppers, onions in a spicy sweet-savory sauce.',
    price: 13.50,
    category: 'Chinese',
    imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    veg: false,
    tags: ['spicy', 'crispy'],
    bestSeller: true,
  },
  {
    name: 'Veg Manchurian',
    description: 'Deep-fried vegetable dumplings tossed in a tangy, umami-rich Manchurian sauce.',
    price: 11.50,
    category: 'Chinese',
    imageUrl: '/uploads/veg-manchurian.jpg',
    rating: 4.5,
    veg: true,
    tags: ['vegetarian', 'tangy'],
    bestSeller: false,
  },
  {
    name: 'Spring Roll',
    description: 'Golden crispy rolls stuffed with seasoned vegetables, served with sweet chili dipping sauce.',
    price: 9.99,
    category: 'Chinese',
    imageUrl: '/uploads/spring-roll.jpg',
    rating: 4.3,
    veg: true,
    tags: ['appetizer', 'crispy'],
    bestSeller: false,
  },
  // ─── Bengaluru Special ────────────────────────────────────
  {
    name: 'Bisi Bele Bath',
    description: 'Karnataka\'s signature spiced rice dish with lentils, vegetables, and a special masala blend.',
    price: 10.99,
    category: 'Bengaluru Special',
    imageUrl: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    veg: true,
    tags: ['traditional', 'comfort food'],
    bestSeller: true,
  },
  {
    name: 'Mysore Masala Dosa',
    description: 'Crispy dosa with a layer of spicy red chutney inside, filled with masala potatoes.',
    price: 11.99,
    category: 'Bengaluru Special',
    imageUrl: '/uploads/mysore-masala-dosa.jpg',
    rating: 4.8,
    veg: true,
    tags: ['spicy', 'crispy', 'signature'],
    bestSeller: true,
  },
  {
    name: 'Ragi Mudde',
    description: 'Traditional finger millet balls served with spicy mutton or vegetable saaru.',
    price: 9.99,
    category: 'Bengaluru Special',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    veg: true,
    tags: ['healthy', 'traditional'],
    bestSeller: false,
  },
  {
    name: 'Filter Coffee',
    description: 'Authentic South Indian filter coffee brewed with chicory, served frothy in a traditional tumbler.',
    price: 4.99,
    category: 'Bengaluru Special',
    imageUrl: 'https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    veg: true,
    tags: ['beverage', 'classic'],
    bestSeller: true,
  },
  // ─── Desserts ─────────────────────────────────────────────
  {
    name: 'Classic Tiramisu',
    description: 'Layered Italian dessert with espresso-soaked ladyfingers, mascarpone cream, and cocoa.',
    price: 8.50,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    veg: true,
    tags: ['sweet', 'italian'],
    bestSeller: true,
  },
  {
    name: 'Gulab Jamun',
    description: 'Soft, golden milk-solid dumplings soaked in fragrant rose and cardamom sugar syrup.',
    price: 6.99,
    category: 'Desserts',
    imageUrl: '/uploads/gulab-jamun.jpg',
    rating: 4.9,
    veg: true,
    tags: ['traditional', 'sweet'],
    bestSeller: true,
  },
  {
    name: 'Rasmalai',
    description: 'Delicate flattened paneer balls immersed in chilled, saffron-infused sweetened milk.',
    price: 7.50,
    category: 'Desserts',
    imageUrl: '/uploads/rasmalai.jpg',
    rating: 4.8,
    veg: true,
    tags: ['traditional', 'chilled'],
    bestSeller: false,
  },
  {
    name: 'Chocolate Lava Cake',
    description: 'Warm, rich chocolate cake with a molten center, served with vanilla ice cream.',
    price: 9.99,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    veg: true,
    tags: ['chocolate', 'indulgent'],
    bestSeller: true,
  },
  // ─── Drinks ───────────────────────────────────────────────
  {
    name: 'Mango Drink',
    description: 'Freshly blended sweet ripe mango juice, served chilled in a glass.',
    price: 5.99,
    category: 'Drinks',
    imageUrl: '/uploads/mango-drink.jpg',
    rating: 4.8,
    veg: true,
    tags: ['refreshing', 'chilled'],
    bestSeller: true,
  },
  {
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime soda with a hint of mint, served chilled.',
    price: 2.99,
    category: 'Drinks',
    imageUrl: '/uploads/fresh-lime-soda.jpg',
    rating: 4.7,
    veg: true,
    tags: ['refreshing', 'citrus'],
    bestSeller: true,
  },
  {
    name: 'Masala Chai',
    description: 'Aromatic Indian spiced tea brewed with ginger, cardamom, cinnamon, and fresh milk.',
    price: 3.99,
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    veg: true,
    tags: ['hot', 'spiced'],
    bestSeller: true,
  },
  {
    name: 'Fresh Lime Soda',
    description: 'Refreshing sparkling lime drink with a choice of sweet, salty, or mixed preparation.',
    price: 3.50,
    category: 'Drinks',
    imageUrl: '/uploads/fresh-lime-soda.jpg',
    rating: 4.3,
    veg: true,
    tags: ['refreshing', 'citrus'],
    bestSeller: false,
  },
  {
    name: 'Cold Coffee',
    description: 'Rich, creamy iced coffee blended with milk and a touch of chocolate. A Bengaluru café staple.',
    price: 5.50,
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    veg: true,
    tags: ['iced', 'creamy'],
    bestSeller: false,
  },
];
